name: Build and Deploy

on: 
  push:
    branches:
      - main
  schedule:
      - cron: "22 22 * * *"
  workflow_dispatch:



jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}  
      
    steps:
    - name: Use coturiv/setup-ionic
      uses: coturiv/setup-ionic@v1
      with:
        cordova-version: 8
        install-java: false
        install-pods: false

    - name: Checkout
      uses: actions/checkout@v1

    - name: Install NPM Modules
      run: |
        npm i -D -E @angular/cli
        npm install
        

    - name: Build
      run: |
        ionic build --prod -- --base-href 'https://codeInstane.github.io/ionic-github-pages-test/'
        ls www
        
        
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: www
        enable_jekyll: true